version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stock-service
    ports:
      - "5433:5432"
    volumes:
      - data:/data
volumes:
  data: {}